name: Draft release

on:
  push:
    tags:
      - '*'

jobs:
  draft_release:
    runs-on: ubuntu-latest
    container: ulauncher/build-image:6.0
    steps:
      - uses: actions/checkout@v3
      - name: Quick test
        run: |
          mypy .
          DISPLAY=:1 xvfb-run pytest test
      - name: Build release
        run: |
          echo "Building Ulauncher version: $GITHUB_REF_NAME"
          DEB_VERSION=$(echo "$GITHUB_REF_NAME" | tr "-" "~")
          ln -s /var/node_modules preferences-src # use node modules from cache
          ./ul build-targz
          ./ul build-deb --deb
          cp /tmp/ulauncher_$VERSION.tar.gz .
          cp /tmp/ulauncher_${DEB_VERSION}_all.deb ulauncher_${VERSION}_all.deb

      - name: Make draft GitHub release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            *.tar.gz
            *.deb
