name: Publish release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    container: ulauncher/build-image:6.0
    steps:
      - uses: actions/checkout@v3
      - name: Publish to Launchpad
        env:
          LAUNCHPAD_SSH_TAR: ${{ secrets.LAUNCHPAD_SSH_TAR }}
          LAUNCHPAD_PUB_KEY: ${{ secrets.LAUNCHPAD_PUB_KEY }}
          LAUNCHPAD_SECRET_KEY: ${{ secrets.LAUNCHPAD_SECRET_KEY }}
          GPGKEY: ${{ secrets.DEB_GPGKEY }}
          PPA: agornostal/ulauncher
        shell: bash
        run: |
          echo "Ref type: $GITHUB_REF_TYPE"
          VERSION=$(./ul version)
          echo "Version: $VERSION"
          # If release name contains prerelease-separator "-", use ulauncher-dev PPA
          if [[ "$VERSION" == *-* ]]; then PPA="agornostal/ulauncher-dev"; fi
          echo "PPA: $PPA"
          echo -n "$LAUNCHPAD_SSH_TAR" | base64 -d > scripts/launchpad.ssh.tar
          echo -n "$LAUNCHPAD_PUB_KEY" | base64 -d > scripts/launchpad-public.key
          echo -n "$LAUNCHPAD_SECRET_KEY" | base64 -d > scripts/launchpad-secret.key
          tar -xvf scripts/launchpad.ssh.tar -C /
          gpg --import "$SRCDIR/scripts/launchpad-public.key"
          gpg --import "$SRCDIR/scripts/launchpad-secret.key"
          # noble  24.04 LTS EOL 2029-04
          # jammy  22.04 LTS EOL 2027-04
          # focal  20.04 LTS EOL 2025-04
          # mantic 23.10     EOL 2024-07
          # lunar  23.04     EOL 2024-01
          ./ul release-deb noble jammy focal mantic lunar

      - name: Publish to AUR
        if: "${{ !contains(github.ref_name, '-') }}"
        uses: friday/aur-publish-action@master
        with:
          new_release: ${{ github.ref_name }}
          package_name: ulauncher
          commit_username: 'Ulauncher'
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_PRIVATE_KEY }}
